code --install-extension ms-dynamics-smb.al
code --install-extension davidfeldhoff.al-codeactions
code --install-extension BartPermentier.al-toolbox
code --install-extension rasmus.al-var-helper
code --install-extension andrzejzwierzchowski.al-code-outline
code --install-extension martonsagi.al-object-designer
code --install-extension bartpermentier.al-toolbox
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension gruntfuggly.todo-tree
code --install-extension heaths.vscode-guid
code --install-extension jamespearson.al-test-runner
code --install-extension ms-vscode.powershell
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension rvanbekkum.xliff-sync
code --install-extension ryu1kn.partial-diff
code --install-extension waldo.crs-al-language-extension
code --install-extension yzhang.markdown-all-in-one